### ISSUE TITLE
The playback misses always the last second of recording

### ISSUE THREAD

**Issue by appfabtech** [tad-iizuka/MP3RecordingSample#1]
I tried your example and when I playback the last second of recorded audio is missing

Thanks

**Comment by tad-iizuka** [comment]
Yes, in this code, to check reached the end of playing by using callback,
 
		self.audioFilePlayer.scheduleSegment(audioFile,
			startingFrame: AVAudioFramePosition(0),
			frameCount: AVAudioFrameCount(self.audioFile.length),
			at: nil,
			completionHandler: self.completion)

But calling timing is a little bit early. If you want to stop pricisely, you might be implemented interval timer see if reached end of audio file length. [See](https://stackoverflow.com/questions/26612992/getting-and-setting-playback-position-avaudioengine?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
