### ISSUE TITLE
App crashing while start recording

### ISSUE THREAD

**Issue by ghost** [tad-iizuka/MP3RecordingSample#2]
Hi @tad-iizuka 

I hope you are doing well. I have an issue with recording the mp3 file. please check below error.

MP3RecordingSample[1692:165854] [avae] AVAEInternal.h:70:_AVAE_Check: required condition is false: [AVAudioIONodeImpl.mm:897:SetOutputFormat: (format.sampleRate == hwFormat.sampleRate)]

Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'

When I checked in simulator its working fine but in the device it is crashing.

**Comment by tad-iizuka** [comment]
I was trying to check see if crashed when MP3 recording. But I couldn't reproduce. Could you tell me what iPhone device do you use? I used the iPhone 6s when reproduce.

**Comment by ghost** [comment]
Thanks for your reply I am using iPhone 6 Plus iOS 12.2 and able to reproduce everytime.

**Comment by tad-iizuka** [comment]
Hi, iOS version is ?

**Comment by tad-iizuka** [comment]
Let me see,  iOS is 12.3.1, Is latest iOS version for iPhone 6 12.2 ? Can you update ?

**Comment by mauryabip** [comment]
hello @tad-iizuka  i am getting same issue. can you update code?
iOS version: 11.4 +

**Comment by tad-iizuka** [comment]
I couldn't reproduce a bug on the iPhone 6s Simulator version 11.4. Can you reproduce on the Simulator?

**Comment by ghost** [comment]
I fixed this issue and also fixed another issue while recording using the iPad sound issue.

**Comment by fukemy** [comment]
same problem, how did u fixed that?

**Comment by tad-iizuka** [comment]
Hi, guys. Sorry for late response. Are you fixed it? If not, try to change sample rate to the 48000.

**Comment by fukemy** [comment]
i know why this problem occur, depend on some action like webrtc call -> sample rate changed to 48000, so the current 44000 make this crash, changed to 48000 make it work

**Comment by fukemy** [comment]
@Sagar021 how did u solved issue in ipad? Thanks

**Comment by tad-iizuka** [comment]
I'm sorry I don't know on iPad.
