### ISSUE TITLE
App crash on sample rate.

### ISSUE THREAD

**Issue by TappChat-dev** [tad-iizuka/MP3RecordingSample#3]
Hi 

My application crash at self.audioEngine.connect(self.audioEngine.inputNode, to: self.mixer, format: format).
Error below:-
com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'

**Comment by tad-iizuka** [comment]
Confirmed at iPhone 12 Pro with/iOS 14.6.  Please debug/check yourself. Sorry.
