### ISSUE TITLE
App crash on sample rate

### ISSUE THREAD

**Issue by ChandaniOS** [tad-iizuka/MP3RecordingSample#4]
Hi 
I have also install pod "mp3lame-for-ios" and add lame.h in bridge file. I will not enable ENABLE_BITCODE to YES because Alamofire require ENABLE_BITCODE  No.
I was added same code in my app.
My application crash at self.audioEngine.connect(self.audioEngine.inputNode, to: self.mixer, format: format).
Error below:-
com.apple.coreaudio.avfaudio', reason: 'required condition is false: format.sampleRate == hwFormat.sampleRate'

**Comment by tad-iizuka** [comment]
Confirmed at iPhone 12 Pro with/iOS 14.6.  Please debug/check yourself. Sorry.
